<?php

namespace App\Services\Yandex\Direct\DTO;

class KeywordsResearchRequest
{
    public function __construct(
        public readonly array $keywords,
        public readonly ?array $geo = null,
        public readonly ?array $language = null,
        public readonly ?array $searchBy = null,
        public readonly ?array $includeRelatedKeywords = null,
        public readonly ?array $includeLowSearchVolume = null,
        public readonly ?array $includeLowCTR = null,
        public readonly ?array $includeLowConversionRate = null,
        public readonly ?array $includeLowRelevance = null,
        public readonly ?array $includeLowCompetition = null,
        public readonly ?array $includeLowQualityScore = null,
        public readonly ?array $includeLowImpressionShare = null,
        public readonly ?array $includeLowClickShare = null,
        public readonly ?array $includeLowConversionShare = null,
        public readonly ?array $includeLowRevenueShare = null,
        public readonly ?array $includeLowProfitShare = null,
        public readonly ?array $includeLowROI = null,
        public readonly ?array $includeLowROAS = null,
        public readonly ?array $includeLowMargin = null,
        public readonly ?array $includeLowProfit = null,
        public readonly ?array $includeLowRevenue = null,
        public readonly ?array $includeLowCost = null,
        public readonly ?array $includeLowClicks = null,
        public readonly ?array $includeLowImpressions = null,
        public readonly ?array $includeLowConversions = null,
        public readonly ?array $includeLowCostPerClick = null,
        public readonly ?array $includeLowCostPerConversion = null,
        public readonly ?array $includeLowCostPerThousandImpressions = null,
        public readonly ?array $includeLowClickThroughRate = null,
        public readonly ?array $includeLowConversionRate = null,
        public readonly ?array $includeLowAveragePosition = null,
        public readonly ?array $includeLowAverageClickPrice = null,
        public readonly ?array $includeLowAverageCost = null,
        public readonly ?array $includeLowAverageConversionPrice = null,
        public readonly ?array $includeLowAverageConversionCost = null,
        public readonly ?array $includeLowAverageConversionRate = null,
        public readonly ?array $includeLowAverageClickThroughRate = null,
        public readonly ?array $includeLowAverageImpressionShare = null,
        public readonly ?array $includeLowAverageClickShare = null,
        public readonly ?array $includeLowAverageConversionShare = null,
        public readonly ?array $includeLowAverageRevenueShare = null,
        public readonly ?array $includeLowAverageProfitShare = null,
        public readonly ?array $includeLowAverageROI = null,
        public readonly ?array $includeLowAverageROAS = null,
        public readonly ?array $includeLowAverageMargin = null,
        public readonly ?array $includeLowAverageProfit = null,
        public readonly ?array $includeLowAverageRevenue = null,
        public readonly ?array $includeLowAverageCost = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            keywords: $data['Keywords'],
            geo: $data['Geo'] ?? null,
            language: $data['Language'] ?? null,
            searchBy: $data['SearchBy'] ?? null,
            includeRelatedKeywords: $data['IncludeRelatedKeywords'] ?? null,
            includeLowSearchVolume: $data['IncludeLowSearchVolume'] ?? null,
            includeLowCTR: $data['IncludeLowCTR'] ?? null,
            includeLowConversionRate: $data['IncludeLowConversionRate'] ?? null,
            includeLowRelevance: $data['IncludeLowRelevance'] ?? null,
            includeLowCompetition: $data['IncludeLowCompetition'] ?? null,
            includeLowQualityScore: $data['IncludeLowQualityScore'] ?? null,
            includeLowImpressionShare: $data['IncludeLowImpressionShare'] ?? null,
            includeLowClickShare: $data['IncludeLowClickShare'] ?? null,
            includeLowConversionShare: $data['IncludeLowConversionShare'] ?? null,
            includeLowRevenueShare: $data['IncludeLowRevenueShare'] ?? null,
            includeLowProfitShare: $data['IncludeLowProfitShare'] ?? null,
            includeLowROI: $data['IncludeLowROI'] ?? null,
            includeLowROAS: $data['IncludeLowROAS'] ?? null,
            includeLowMargin: $data['IncludeLowMargin'] ?? null,
            includeLowProfit: $data['IncludeLowProfit'] ?? null,
            includeLowRevenue: $data['IncludeLowRevenue'] ?? null,
            includeLowCost: $data['IncludeLowCost'] ?? null,
            includeLowClicks: $data['IncludeLowClicks'] ?? null,
            includeLowImpressions: $data['IncludeLowImpressions'] ?? null,
            includeLowConversions: $data['IncludeLowConversions'] ?? null,
            includeLowCostPerClick: $data['IncludeLowCostPerClick'] ?? null,
            includeLowCostPerConversion: $data['IncludeLowCostPerConversion'] ?? null,
            includeLowCostPerThousandImpressions: $data['IncludeLowCostPerThousandImpressions'] ?? null,
            includeLowClickThroughRate: $data['IncludeLowClickThroughRate'] ?? null,
            includeLowConversionRate: $data['IncludeLowConversionRate'] ?? null,
            includeLowAveragePosition: $data['IncludeLowAveragePosition'] ?? null,
            includeLowAverageClickPrice: $data['IncludeLowAverageClickPrice'] ?? null,
            includeLowAverageCost: $data['IncludeLowAverageCost'] ?? null,
            includeLowAverageConversionPrice: $data['IncludeLowAverageConversionPrice'] ?? null,
            includeLowAverageConversionCost: $data['IncludeLowAverageConversionCost'] ?? null,
            includeLowAverageConversionRate: $data['IncludeLowAverageConversionRate'] ?? null,
            includeLowAverageClickThroughRate: $data['IncludeLowAverageClickThroughRate'] ?? null,
            includeLowAverageImpressionShare: $data['IncludeLowAverageImpressionShare'] ?? null,
            includeLowAverageClickShare: $data['IncludeLowAverageClickShare'] ?? null,
            includeLowAverageConversionShare: $data['IncludeLowAverageConversionShare'] ?? null,
            includeLowAverageRevenueShare: $data['IncludeLowAverageRevenueShare'] ?? null,
            includeLowAverageProfitShare: $data['IncludeLowAverageProfitShare'] ?? null,
            includeLowAverageROI: $data['IncludeLowAverageROI'] ?? null,
            includeLowAverageROAS: $data['IncludeLowAverageROAS'] ?? null,
            includeLowAverageMargin: $data['IncludeLowAverageMargin'] ?? null,
            includeLowAverageProfit: $data['IncludeLowAverageProfit'] ?? null,
            includeLowAverageRevenue: $data['IncludeLowAverageRevenue'] ?? null,
            includeLowAverageCost: $data['IncludeLowAverageCost'] ?? null,
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'Keywords' => $this->keywords,
            'Geo' => $this->geo,
            'Language' => $this->language,
            'SearchBy' => $this->searchBy,
            'IncludeRelatedKeywords' => $this->includeRelatedKeywords,
            'IncludeLowSearchVolume' => $this->includeLowSearchVolume,
            'IncludeLowCTR' => $this->includeLowCTR,
            'IncludeLowConversionRate' => $this->includeLowConversionRate,
            'IncludeLowRelevance' => $this->includeLowRelevance,
            'IncludeLowCompetition' => $this->includeLowCompetition,
            'IncludeLowQualityScore' => $this->includeLowQualityScore,
            'IncludeLowImpressionShare' => $this->includeLowImpressionShare,
            'IncludeLowClickShare' => $this->includeLowClickShare,
            'IncludeLowConversionShare' => $this->includeLowConversionShare,
            'IncludeLowRevenueShare' => $this->includeLowRevenueShare,
            'IncludeLowProfitShare' => $this->includeLowProfitShare,
            'IncludeLowROI' => $this->includeLowROI,
            'IncludeLowROAS' => $this->includeLowROAS,
            'IncludeLowMargin' => $this->includeLowMargin,
            'IncludeLowProfit' => $this->includeLowProfit,
            'IncludeLowRevenue' => $this->includeLowRevenue,
            'IncludeLowCost' => $this->includeLowCost,
            'IncludeLowClicks' => $this->includeLowClicks,
            'IncludeLowImpressions' => $this->includeLowImpressions,
            'IncludeLowConversions' => $this->includeLowConversions,
            'IncludeLowCostPerClick' => $this->includeLowCostPerClick,
            'IncludeLowCostPerConversion' => $this->includeLowCostPerConversion,
            'IncludeLowCostPerThousandImpressions' => $this->includeLowCostPerThousandImpressions,
            'IncludeLowClickThroughRate' => $this->includeLowClickThroughRate,
            'IncludeLowConversionRate' => $this->includeLowConversionRate,
            'IncludeLowAveragePosition' => $this->includeLowAveragePosition,
            'IncludeLowAverageClickPrice' => $this->includeLowAverageClickPrice,
            'IncludeLowAverageCost' => $this->includeLowAverageCost,
            'IncludeLowAverageConversionPrice' => $this->includeLowAverageConversionPrice,
            'IncludeLowAverageConversionCost' => $this->includeLowAverageConversionCost,
            'IncludeLowAverageConversionRate' => $this->includeLowAverageConversionRate,
            'IncludeLowAverageClickThroughRate' => $this->includeLowAverageClickThroughRate,
            'IncludeLowAverageImpressionShare' => $this->includeLowAverageImpressionShare,
            'IncludeLowAverageClickShare' => $this->includeLowAverageClickShare,
            'IncludeLowAverageConversionShare' => $this->includeLowAverageConversionShare,
            'IncludeLowAverageRevenueShare' => $this->includeLowAverageRevenueShare,
            'IncludeLowAverageProfitShare' => $this->includeLowAverageProfitShare,
            'IncludeLowAverageROI' => $this->includeLowAverageROI,
            'IncludeLowAverageROAS' => $this->includeLowAverageROAS,
            'IncludeLowAverageMargin' => $this->includeLowAverageMargin,
            'IncludeLowAverageProfit' => $this->includeLowAverageProfit,
            'IncludeLowAverageRevenue' => $this->includeLowAverageRevenue,
            'IncludeLowAverageCost' => $this->includeLowAverageCost,
        ]);
    }
} 